server:
  port: 9527

spring:
  application:
    name: springcloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: zuul9527.com
    prefer-ip-address: true

zuul:
  routes:
    my.serviceId: springcloud-provider-dept
    my.path: /mydept/**
  ignored-services: springcloud-provider-dept  # 不能再使用这个路径访问



info:
  app.name: engulf-springcloud
